/** AUTO-GENERATED by studio compiler. Do not edit directly. */

import { Dashboard } from "@/components/generated";

export default function Page() {
  return (
    <>
      <Dashboard />
    </>
  );
}
