/** AUTO-GENERATED by studio compiler. Do not edit directly. */

import { LandingPage } from "@/components/generated";

export default function Page() {
  return (
    <>
      <LandingPage />
    </>
  );
}
