/** AUTO-GENERATED by studio compiler. Do not edit directly. */

import { BlankTest } from "@/components/generated";

export default function Page() {
  return (
    <>
      <BlankTest />
    </>
  );
}
