/** AUTO-GENERATED by studio compiler. Do not edit directly. */

import { NextHome } from "@/components/generated";

export default function Page() {
  return (
    <>
      <NextHome />
    </>
  );
}
