/** AUTO-GENERATED by studio compiler. Do not edit directly. */

import { AboutPage } from "@/components/generated";

export default function Page() {
  return (
    <>
      <AboutPage />
    </>
  );
}
