/** AUTO-GENERATED by studio compiler. Do not edit directly. */

import { TestPage } from "@/components/generated";

export default function Page() {
  return (
    <>
      <TestPage />
    </>
  );
}
