import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Receives DS token CSS variables from the Studio preview page via postMessage
            and injects them as a <style> tag so the preview iframe renders with DS colours. */}
        <script dangerouslySetInnerHTML={{ __html: `
(function(){
  window.addEventListener('message',function(e){
    if(!e.data||e.data.type!=='studio:previewTokens'||typeof e.data.css!=='string')return;
    var id='studio-preview-tokens';
    var el=document.getElementById(id);
    if(!el){el=document.createElement('style');el.id=id;document.head.appendChild(el);}
    el.textContent=e.data.css;
  });
})();
        `}} />
        <link
          rel="preconnect"
          href="https://fonts.googleapis.com"
        />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Toaster position="bottom-right" richColors />
      </body>
    </html>
  );
}
