import { compile } from "./compile";
import {
  publishToGitHub,
  type PublishMode,
  type PublishSummary,
} from "../adapters/github/publish";

const modeFromArgs = (): PublishMode => {
  if (process.argv.includes("--pr")) {
    return "pr";
  }
  if (process.argv.includes("--commit")) {
    return "commit-only";
  }
  if (process.argv.includes("--dry")) {
    return "dry-run";
  }
  const arg = process.argv.find((item) => item.startsWith("--mode="));
  if (!arg) {
    return "dry-run";
  }
  const value = arg.split("=")[1];
  if (value === "commit-only" || value === "dry-run" || value === "pr") {
    return value;
  }
  return "dry-run";
};

const formatSummaryTable = (summary: {
  created: number;
  modified: number;
  deleted: number;
}): string => {
  const lines = [
    "Summary",
    "-------",
    `created:  ${summary.created}`,
    `modified: ${summary.modified}`,
    `deleted:  ${summary.deleted}`,
  ];
  return lines.join("\n");
};

const buildPrBody = (
  timestamp: string,
  summary: PublishSummary
): string => {
  const lines = [
    `Generated by Studio compiler at ${timestamp}`,
    "",
    "## Summary",
    `- created: ${summary.created}`,
    `- modified: ${summary.modified}`,
    `- deleted: ${summary.deleted}`,
  ];

  if (summary.paths.length > 0) {
    lines.push("", "## Changed files");
    summary.paths.forEach((filePath) => lines.push(`- \`${filePath}\``));
  }

  return lines.join("\n");
};

export async function publish(): Promise<void> {
  const files = await compile({ write: false });
  const mode = modeFromArgs();

  // Use a stable branch name so duplicate PR detection works. If a PR
  // already exists for this branch, the adapter will report it instead of
  // creating a second one.
  const headBranch = "studio/pending";

  // For PR mode we need the summary first to build the body, but the
  // adapter needs the body at call time. We solve this by doing a two-pass
  // approach: first run a dry-run to get the summary, then run the real
  // mode with the body built from the summary.
  let body: string | undefined;
  if (mode === "pr") {
    const dryResult = await publishToGitHub({
      repoPath: process.cwd(),
      baseBranch: "main",
      headBranch,
      title: "chore(studio): UI update",
      mode: "dry-run",
      files,
    });
    body = buildPrBody(new Date().toISOString(), dryResult);
  }

  const result = await publishToGitHub({
    repoPath: process.cwd(),
    baseBranch: "main",
    headBranch,
    title: "chore(studio): UI update",
    body,
    mode,
    files,
  });

  console.log(formatSummaryTable(result));
  if (result.paths.length > 0) {
    console.log("\nChanged files:");
    result.paths.forEach((filePath) => console.log(`- ${filePath}`));
  }

  if (mode === "dry-run" && result.diff.length > 0) {
    console.log("\nDiff:\n");
    console.log(result.diff);
  }

  if (result.prUrl) {
    console.log(`\nPR: ${result.prUrl}`);
  }
}

if (require.main === module) {
  publish().catch((error) => {
    console.error(error);
    process.exit(1);
  });
}
