/** AUTO-GENERATED by studio compiler. Do not edit directly. */

import { HomepageDesktop } from "@/components/generated";

export default function Page() {
  return (
    <>
      <HomepageDesktop />
    </>
  );
}
