/** AUTO-GENERATED by studio compiler. Do not edit directly. */

import { TestScreenAnt } from "@/components/generated";

export default function Page() {
  return (
    <>
      <TestScreenAnt />
    </>
  );
}
