/** AUTO-GENERATED by studio compiler. Do not edit directly. */

import { BigBlank } from "@/components/generated";

export default function Page() {
  return (
    <>
      <BigBlank />
    </>
  );
}
