/** AUTO-GENERATED by studio compiler. Do not edit directly. */

import { FigmaImport } from "@/components/generated";

export default function Page() {
  return (
    <>
      <FigmaImport />
    </>
  );
}
