import type { Node, ScreenSpec } from "../types";

export type EmittedFile = {
  path: string;
  contents: string;
};

type EmitResult = {
  jsx: string;
  imports: Set<string>;
};

const GAP_MAP: Record<string, string> = {
  xs: "1",
  sm: "2",
  md: "4",
  lg: "6",
  xl: "8",
};

const resolveGap = (gap?: string): string => {
  if (!gap) {
    return GAP_MAP.lg;
  }
  return GAP_MAP[gap] ?? GAP_MAP.lg;
};

const escapeText = (value: string): string =>
  value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

const mergeImports = (target: Set<string>, source: Set<string>): void => {
  source.forEach((item) => target.add(item));
};

const indentLines = (value: string, spaces: number): string => {
  const pad = " ".repeat(spaces);
  return value
    .split("\n")
    .map((line) => (line.length > 0 ? `${pad}${line}` : line))
    .join("\n");
};

export function emitNode(node: Node): EmitResult {
  switch (node.type) {
    case "heading": {
      return {
        jsx: `<h1 className="text-xl font-semibold">${escapeText(
          node.text
        )}</h1>`,
        imports: new Set(),
      };
    }
    case "text": {
      const content = escapeText(node.text);
      if (node.variant === "body") {
        return {
          jsx: `<p className="text-base">${content}</p>`,
          imports: new Set(),
        };
      }
      if (node.variant === "muted") {
        return {
          jsx: `<p className="text-sm text-muted-foreground">${content}</p>`,
          imports: new Set(),
        };
      }
      return { jsx: `<p>${content}</p>`, imports: new Set() };
    }
    case "card": {
      const children = emitNodes(node.children);
      const body = children.jsx
        ? `\n${indentLines(children.jsx, 6)}\n    `
        : "";
      return {
        jsx: `<Card>\n  <div className="p-4">${body}</div>\n</Card>`,
        imports: new Set([
          "@/components/ui/card",
          ...Array.from(children.imports),
        ]),
      };
    }
    case "button": {
      return {
        jsx: `<Button>${escapeText(node.label)}</Button>`,
        imports: new Set(["@/components/ui/button"]),
      };
    }
    case "stack": {
      return emitStack(node.children, node.gap, false);
    }
  }
}

export function emitNodes(nodes: Node[]): EmitResult {
  const imports = new Set<string>();
  const parts = nodes.map((node) => {
    const result = emitNode(node);
    mergeImports(imports, result.imports);
    return result.jsx;
  });

  return { jsx: parts.join("\n"), imports };
}

const emitStack = (
  nodes: Node[],
  gap: string | undefined,
  includePadding: boolean
): EmitResult => {
  const children = emitNodes(nodes);
  const resolvedGap = resolveGap(gap);
  const body = children.jsx ? `\n${indentLines(children.jsx, 2)}\n` : "";
  const padding = includePadding ? " p-6" : "";
  return {
    jsx: `<div className="flex flex-col gap-${resolvedGap}${padding}">${body}</div>`,
    imports: children.imports,
  };
};

const importLineForPath = (importPath: string): string => {
  switch (importPath) {
    case "@/components/ui/button":
      return 'import { Button } from "@/components/ui/button";';
    case "@/components/ui/card":
      return 'import { Card } from "@/components/ui/card";';
    default:
      throw new Error(`Unsupported import path: ${importPath}`);
  }
};

export function emitHome(spec: ScreenSpec): EmittedFile[] {
  const header =
    "/** AUTO-GENERATED by studio compiler. Do not edit directly. */\n\n";
  const pageContents = `${header}import { Home } from "@/components/generated";

export default function Page() {
  return <Home />;
}
`;

  const emitted = emitStack(spec.children, spec.gap, true);
  const body = emitted.jsx ? `\n${indentLines(emitted.jsx, 4)}\n` : "\n";
  const importLines = Array.from(emitted.imports)
    .sort((a, b) => a.localeCompare(b))
    .map((importPath) => importLineForPath(importPath));
  const imports = importLines.length > 0 ? `${importLines.join("\n")}\n\n` : "";
  const homeContents = `${header}${imports}export function Home() {
  return (${body}  );
}
`;
  const indexContents =
    "/** AUTO-GENERATED by studio compiler. Do not edit directly. */\n\n" +
    'export { Home } from "./Home.generated";\n';

  return [
    { path: "apps/web/app/page.tsx", contents: pageContents },
    {
      path: "apps/web/components/generated/Home.generated.tsx",
      contents: homeContents,
    },
    {
      path: "apps/web/components/generated/index.ts",
      contents: indexContents,
    },
  ];
}
